// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoGx3Gxy6utfx_O2xk7K2xNBs0QGlBdDc',
    appId: '1:272345755335:web:ae2e4b48863257185cd8e2',
    messagingSenderId: '272345755335',
    projectId: 'loginfire-8de07',
    authDomain: 'loginfire-8de07.firebaseapp.com',
    storageBucket: 'loginfire-8de07.appspot.com',
    measurementId: 'G-0W5BX4XPXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJtE5s7YKLG6z9xoH7jho7IrnGMMH3urA',
    appId: '1:272345755335:android:5bad5112eeed1a5a5cd8e2',
    messagingSenderId: '272345755335',
    projectId: 'loginfire-8de07',
    storageBucket: 'loginfire-8de07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATONnFTz1dyRe4v2JmwIqpP-3bgcpm6vU',
    appId: '1:272345755335:ios:4a46de98da3e9a5a5cd8e2',
    messagingSenderId: '272345755335',
    projectId: 'loginfire-8de07',
    storageBucket: 'loginfire-8de07.appspot.com',
    iosBundleId: 'com.example.loginfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATONnFTz1dyRe4v2JmwIqpP-3bgcpm6vU',
    appId: '1:272345755335:ios:b3866fab3f8fa4a15cd8e2',
    messagingSenderId: '272345755335',
    projectId: 'loginfire-8de07',
    storageBucket: 'loginfire-8de07.appspot.com',
    iosBundleId: 'com.example.loginfire.RunnerTests',
  );
}
